package lk.java.bcd.auction.session;

import jakarta.annotation.security.DeclareRoles;
import jakarta.annotation.security.RolesAllowed;
import jakarta.ejb.EJB;
import jakarta.ejb.Stateless;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import lk.java.bcd.auction.entity.AuctionItem;
import lk.java.bcd.auction.entity.Bid;
import lk.java.bcd.auction.entity.User;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

@Stateless
@DeclareRoles({"USER", "ADMIN"}) // Declaring roles used by this EJB
public class AuctionServiceBean implements AuctionService {

    // In-memory storage for simplicity. Replace with database interaction.
    // In-memory storage for simplicity. Replace with database interaction.
    // private static final Map<Long, AuctionItem> auctionItems = new ConcurrentHashMap<>();
    // private static final AtomicLong currentId = new AtomicLong(1); // No longer needed for item ID with IDENTITY strategy

    @PersistenceContext(unitName = "auctionPU")
    private EntityManager em;

    @EJB
    private UserService userService;


    @Override
    @RolesAllowed("USER") // Only authenticated users with role USER can create items
    public AuctionItem createAuctionItem(AuctionItem item) {
        // ID is auto-generated by the database, so no need to set it manually.
        if (item.getCurrentPrice() == 0 && item.getStartingPrice() > 0) {
            item.setCurrentPrice(item.getStartingPrice());
        }
        em.persist(item);
        return item;
    }

    @Override
    public AuctionItem findAuctionItemById(Long id) {
        return em.find(AuctionItem.class, id);
    }

    @Override
    public List<AuctionItem> getAllAuctionItems() {
        return em.createQuery("SELECT ai FROM AuctionItem ai ORDER BY ai.endTime DESC", AuctionItem.class).getResultList();
    }

    @Override
    @RolesAllowed("USER") // Only authenticated users with role USER can place bids
    public AuctionItem placeBid(Long itemId, double bidAmount, String username) throws AuctionException, UserNotFoundException, Exception {
        // In a fully secured setup with EJB security context propagation,
        // the username could potentially be derived from sessionContext.getCallerPrincipal().getName()
        // instead of being passed as a parameter. This would make the EJB method signature
        // independent of how the caller obtains the username.
        // For example:
        // @Resource
        // private SessionContext sessionContext;
        // String callerUsername = sessionContext.getCallerPrincipal().getName();
        // However, this requires proper security setup and login mechanisms that establish the principal.
        // The current approach of passing username is fine for now.

        AuctionItem item = findAuctionItemById(itemId);
        if (item == null) {
            throw new Exception("Auction item with ID " + itemId + " not found.");
        }

        User bidder = userService.findUserByUsername(username);
        if (bidder == null) {
            throw new UserNotFoundException("User with username '" + username + "' not found.");
        }

        // Validation
        if (item.getEndTime() == null || !item.getEndTime().after(new Date())) {
            throw new AuctionException("Auction for item '" + item.getName() + "' has ended or has no end time.");
        }

        // Check if bidder is the item owner (if such a rule exists - not implemented here)
        // if (item.getOwner().equals(bidder)) {
        // throw new AuctionException("You cannot bid on your own item.");
        // }

        double priceToCheck = item.getBids().isEmpty() ? item.getStartingPrice() : item.getCurrentPrice();
        if (bidAmount <= priceToCheck) {
            throw new AuctionException("Your bid of " + String.format("%.2f", bidAmount) +
                                     " must be greater than the current price of " + String.format("%.2f", priceToCheck) + ".");
        }

        // All checks passed, create and process the bid
        Bid newBid = new Bid(item, bidder, bidAmount);
        // The Bid constructor sets the bidTime.

        // Add bid to item's collection and update current price
        item.addBid(newBid); // This helper should also set newBid.setAuctionItem(item)
        item.setCurrentPrice(bidAmount);
        // item.setWinningUser(bidder); // Update winning user with each valid higher bid

        // Persist the new Bid. If CascadeType.PERSIST or ALL is on AuctionItem.bids, this might be redundant
        // but explicit persist is safer and clearer.
        em.persist(newBid);

        // Merge the updated AuctionItem
        AuctionItem updatedItem = em.merge(item);

        return updatedItem;
    }
}
